config/routes.rb
Tawasol::Application.routes.draw do

  resources :polls

  get 'tags/:tag', to: 'initiatives#list', as: :tag

   match ':controller(/:action(/:id))(.:format)'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :initiative
	validates :content, 
	presence: true
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base

	# Associations
	
	belongs_to :sector
	has_many :comments
	has_many :polls

	#users vs initiatives
	has_many :poll_votes
	has_many :users, through: :poll_votes
		

	#tagging
	attr_accessible :description, :title, :tag_list, :region, :img, :sector_id
	has_many :taggings
	has_many :tags, through: :taggings

	
	def self.tagged_with(name)
	  Tag.find_by_name!(name).initiatives
	end

	def tag_list
	  tags.map(&:name).join(", ")
	end

	def tag_list=(names)
	  self.tags = names.split(",").map do |n|
	    	Tag.where(name: n.strip).first_or_create!
	  end
	end
	

	#search scope by title & Region of initiative
	scope :searchRegion, lambda{|searchRegion| where (["region LIKE ?","%#{searchRegion}%"])}
	scope :searchTitle, lambda{|searchTitle| where (["title LIKE ?","%#{searchTitle}%"])}


	#paperclip:
	
	# has_attached_file :photo, :styles => { :small => "150x150>" },
	#                   :default_url => "/images/:style/missing.png"

	# validates_attachment_presence :photo
	# validates_attachment_size :photo, :less_than => 5.megabytes
	# validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :questions, :dependent => :destroy
	belongs_to :initiative
	
	accepts_nested_attributes_for :questions, :reject_if => lambda { |x| x[:content].blank? }, :allow_destroy => true
end

app/models/poll_vote.rb
class PollVote < ActiveRecord::Base
	belongs_to :user
	belongs_to :initiative

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :poll
	has_many :answers, :dependent => :destroy
	accepts_nested_attributes_for :answers, :reject_if => lambda { |x| x[:content].blank? }, :allow_destroy => true
end

app/models/sector.rb
class Sector < ActiveRecord::Base

	#Association with sector 1-M
	has_many :initiatives  


end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :initiatives, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :initiative
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :poll_votes
	has_many :initiatives, through :poll_votes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController

	def new
   
	   	@sectors=Sector.all
	  	initiative=Initiative.new
	  	 
	end

	def create
	  	 initiative=Initiative.new(:tag_list => params[:tag_list])
		 initiative.title=params[:title]
	  	 initiative.description=params[:description]
	  	 initiative.img=params[:img]
	  	 initiative.region=params[:region]
	  	 initiative.sector_id=params[:sectorID].to_i
	  	 
	  	 if initiative.save
	  	 	redirect_to(:controller => 'polls', :action => 'new', :initiative_id => initiative.id)
	  	 else
	  	 	render('new')

		end
	end
	
	def list
		@sectors = Sector.all
		case 
		when params[:searchTitle]
			@initiatives = Initiative.searchTitle(params[:searchTitle])
		when params[:tag]
			@initiatives = Initiative.tagged_with(params[:tag])
		when params[:searchRegion]
			@initiatives = Initiative.searchRegion(params[:searchRegion])
		else
			@initiatives = Initiative.all
		end
	end
	
	def show
		@sector = Sector.find(params[:id_sector])
		@polls = Poll.where("initiative_id" => params[:id_initiative])
		@initiative = Initiative.find(params[:id_initiative])
		@comment = Comment.new
		@comment.content = params[:content]
		@comment.commentable_id = params[:id_initiative]
		@comment.commentable_type = "initiative"
		@comment.save
		@comments = Comment.where("commentable_id" => params[:id_initiative]).where("commentable_type" => "initiative")
	end


end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  
  # GET /polls
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /polls/new
  # GET /polls/new.json
  def new 
    @poll = Poll.new
    @initiative_id = params[:initiative_id].to_i
     2.times do 
       question = @poll.questions.build
       3.times{question.answers.build}
     end

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find(params[:id])
  end

  # POST /polls
  def create
    @poll = Poll.new(params[:poll])


    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll}
     else
        format.html { render action: "new" }
     end
    end
  end

  # PUT /polls/1
  # PUT /polls/1.json
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll}
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /polls/1
  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
    end
  end
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController


def index
    list 
    render('list')
end

def list
	@sectors = Sector.all	
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/initiatives/_form.html.erb
<table>


	<tr>
		<td>عناون المبادرة</td>
		<td><%= f.text_field(:title)%></td>
	</tr>
	<tr>
		<td>تفاصيل المبادرة</td>
		<td><%= f.text_area(:description)%></td>
	</tr>
	<tr>
		<td>المنطقة المبادرة</td>
		<td>
			<%= select_tag(:region, options_for_select([['أبو ظبي', 1], ['دبي', 2], ['الشارقة', 3], ['عجمان', 4], ['أم القيوين', 5], ['رأس الخيمة', 6], ['الفجيرة', 7]], selected: :region )) %>
		</td>
	</tr>

	<tr>
		<td>صورة</td>
		<td><%= f.text_field(:img)%></td>
	</tr>
	

</table>

app/views/initiatives/list.erb
<html lang="ar" dir="rtl">
<%= link_to('عمل مبادرة جديدة',{:action => 'new'})%>

<!-- search box -->

<br>
<form action="/initiatives/list" method="get">
	<p>
		<input type="text" name="searchTitle">
	  	<input type="submit" value="إبحث بالإسم">
	</p>  
</form>

<br>


<h3>كل المبادرات</h3>        
<!-- list all initiatives -->

<% @initiatives.each do |initiative|%>

	عنوان: <%= link_to(initiative.title, {:action => 'show', :id_initiative => initiative.id, :id_sector => initiative.sector_id})%>
	<br>
	بإمارة: <%= link_to(initiative.region, {:controller => 'initiatives' ,:action => "list", :searchRegion => initiative.region})%>
	<br>
	الوصف: <%= initiative.description %>
	<br>
	التصنيفات: <%= raw initiative.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
	 	<br>
	 	<br>
<%end%>

</html>

app/views/initiatives/new.html.erb
<html lang="ar" dir="rtl">


<script src="jquery.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$("#createInitiative").hide();
  		$("button").click(function(){
    	$("#sectors").hide();
    	$("#createInitiative").show();
        });
  	});


	function clicked(item) {
    	var sectorId=$(item).attr("id");
    	var sectorName=$(item).attr("sectorname");
    	var sectorDesc=$(item).attr("sectordesc");
    	// alert(sectorName);
    	// alert(if sectorDesc == Array);
    	// alert(sectorName.type);

    	$("#sectorName").html(sectorName);
    	$("#sectorDesc").html(sectorDesc);

    	$("#form").append("<input id='hidden' type='hidden' name='sectorID' value="+sectorId+" >"); 
   	}
</script>

<div id="sectors">

	<% @sectors.each do |sector| %>
		<button onclick="clicked(this);" id=<%=sector.id%> sectorname=<%=sector.sectorname%> sectordesc=<%= sector.description%> ><%=sector.sectorname%> </button>
		<%= sector.description%><br>
	<%end %>

</div>
<div id="createInitiative">
	<form id="form" method="post" action="create">
		<table>
			<tr>
				<td><span>القطاع</span></td>
				<td><span id="sectorName">الهوية</span>
				<br><span id="sectorDesc">الهوية</span></td>

			</tr>
			<tr>
				<td><span>عنوان المبادرة</span></td>
				<td><input type="text" name="title"></td>
			</tr>
			<tr>
				<td><span>تفاصيل المبادرة</span></td>
				<td><textarea name="description"></textarea></td>
			</tr>
			<tr>
				<td><span>المنطقة المبادرة</span></td>
				<td>
					<select name="region">
						<option value="أبو ظبي">أبو ظبي</option>
						<option value="الشارقة">الشارقة</option>
						<option value="عجمان">عجمان</option>
						<option value="أم القيوين">أم القيوين</option>
						<option value="دبي">دبي</option>
						<option value="الفجيرة">الفجيرة</option>
						<option value="رأس الخيمة">رأس الخيمة</option>

					</select>
				</td>
			</tr>
			<tr>
				<td><span>تصنيفات</span></td>
				<td><input type="text" name="tag_list"></td>
			</tr>
			<tr>
				<td><td rowspan=4 colspan=4 ><input type="file" name="img"></td>
			</tr>
						<tr>
				<td colspan=2><input type="submit" value="استمرار"></td>
			</tr>
		</table>
	</form>
</div>

<%= link_to("عمل تصويت", { :controller => 'polls', :action => 'new'})%>

app/views/initiatives/new_backup.html.erb
<html lang="ar" dir="rtl">

<h2>إنشاء مبادرة</h2>


	<%= form_for(:initiative, :url => {:action => 'create'}) do |i| %>

		<!-- <%= render(:partial => "form", :locals => {:f => i}) %> -->
		
		
		<table>

		<tr>
			<td>مبادرة بقطاع</td>
			<td><%= @sector_name%> <br> <%= @sector_description %> </td>

		</tr>	
		<tr>
			<td>عناون المبادرة</td>
			<td><%= i.text_field(:title)%></td>
		</tr>
		<tr>
			<td>تفاصيل المبادرة</td>
			<td><%= i.text_area(:description)%></td>
		</tr>
		<tr>
			<td>المنطقة المبادرة</td>
			<td><%= i.select(:region, options_for_select([['أبو ظبي'], ['دبي'], ['الشارقة'], ['عجمان'], ['أم القيوين'], ['رأس الخيمة']])) %></td>
		</tr>

		<tr>
			<td>صورة</td>
			<td><%= i.text_field(:img)%></td>
		</tr>
		

		<tr>
			<td>القطاع</td>
			<td><%= i.hidden_field :sector_id, :value => @sector_id%></td>
			<!-- <td><%= i.number_field :sector_id, :value => @sector_id%></td> -->

		</tr>
		<br>
		
		<tr>
			<td>تصنيفات</td>
			<td>التصنيفات</td>
		</tr>
		<tr>
			<td><%= submit_tag("إستمرار")%></td>	
		</tr>
		


	</table>


	<%end%>
</html>

app/views/initiatives/show.html.erb
<html lang="ar" dir="rtl">


القطاع: <%= link_to(@sector.sectorname) %>
<br>
إسم المبادرة: <%= @initiative.title %>
<br>
وصف المبادرة: <%= @initiative.description%>
<br>
بإمارة: <%= link_to(@initiative.region, {:controller => 'initiatives' ,:action => "list", :searchRegion => @initiative.region})%>


<br>
<br>
<div>
<% @polls.each do |poll|%>
<%= poll.name %>


	<% for question in poll.questions %>
		<ol>
		<li><%= question.content%></li>
			<ul>	
			<form method="post" action="create">
			<%for answer in question.answers %>
					
						<input type="radio" name="ans" value= "<%=answer.id%>"><%=answer.content%>
				<br>
				<%end%>
						<input type="submit" value="صوت">

			</form>


			</ul>
		</ol>
	<%end%>
	

<%end%>

</p>


</div>



<br>
<div>
التعليقات
<br>

<form method="Post">
	<textarea name="content"></textarea><br>
	<input type="submit" value="ارسل">
</form>

<%@comments.each do |comment|%>
<div>
	<span><%=comment.content%></span>
	<span><%=comment.created_at%></span>
</div>
<%end%>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tawasol</title>
  <br>
  <br>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/polls/_answers_fields.html.erb
<br>
<%= f.label :content, "الإجابة" %><br>
<%= f.text_field :content %><br>
<%=f.label :_destroy, "حذف الإجابة"%>
<%=f.check_box :_destroy%>
<br>

app/views/polls/_form.html.erb
<%= form_for(@poll) do |f| %>
  
  <% if @poll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poll.errors.count, "error") %> prohibited this poll from being saved:</h2>

      <ul>
      <% @poll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= @var %>

  <div class="field">
    <%= f.label :name ,"إسم التصويت" %><br />
    <%= f.text_field :name %>
    <%= f.hidden_field :initiative_id, :value => @initiative_id%>
  </div>

  <div>
    <%= f.fields_for :questions do |builder|%>
      <%= render 'questions_fields', :f => builder%> 
    <%end%>  
  </div>
  




  <div class="actions">
    <%= f.submit "تسجيل الأسئلة" %>
  </div>

<% end %>

app/views/polls/_questions_fields.html.erb
<br>
<br>
<%= f.label :content, "سؤال:"%><br>
<%= f.text_area :content, :rows => 2%><br>
<%= f.label :_destroy, "حذف السؤال:"%>
<%= f.check_box :_destroy%>

<%= f.fields_for :answers do |builder|%>
	<%= render 'answers_fields', :f => builder%>
<%end%>

app/views/polls/edit.html.erb
<html lang="ar" dir="rtl">

<h1>تعديل التصويت</h1>

<%= render 'form' %>

<%= link_to 'عرض كل الأسئلة', @poll %> |
<%= link_to 'عودة', polls_path %>
<html>

app/views/polls/index.html.erb
<html lang="ar" dir="rtl">
<h1>عرض كل الأسئلة</h1>

<table>
  <tr>
    <th>اسم التصويت</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @polls.each do |poll| %>
  <tr>
    <td><%= poll.name %></td>
    <td><%= link_to 'عرض', poll %></td>
    <td><%= link_to 'تعديل', edit_poll_path(poll) %></td>
    <td><%= link_to 'إزالة', poll, method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'عمل تصويت جديد', new_poll_path %>
</html>

app/views/polls/new.html.erb
<html lang="ar" dir="rtl">
<h1>عمل تصويت جديد</h1>

<%= render 'form' %>

<%= link_to 'عودة', polls_path %>
</html>

app/views/polls/show.html.erb
<html lang="ar" dir="rtl">
<p>
  <b>إسم التصويت:</b>
  <%= @poll.name %>
</p>
<p>
	<% for question in @poll.questions %>
	<ol>
	<li><%= question.content%></li>
		<ul>
			<%for answer in question.answers %>
				<li><%=answer.content%></li>
			<%end%>
		</ul>
	</ol>
	<%end%>
</p>


<%= link_to 'تعديل', edit_poll_path(@poll) %> |
<%= link_to 'عودة', polls_path %>
</html>

app/views/sectors/list.html.erb
<html lang="ar" dir="rtl">


	<table>
		<tr>
		<th>القسم</th>
		<th>الوصف</th>
		</tr>

		<% @sectors.each do |sector|%>
		<tr>
			<td><%= link_to(sector.sectorname, {:controller => 'initiatives', :action => 'new', :id => sector.id, :sectorname => sector.sectorname, :desc => sector.description})  %></td>
			<td><%= sector.description %></td>
		</tr>

		<%end%>
	</table>

</html>